-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 14:32:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `book_store` ;

-- -----------------------------------------------------
-- Table `book_store`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(150) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `status` INT NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `verify` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`account_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`account_address` (
  `account_address_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `account_id` INT NOT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `id_province` INT NOT NULL,
  `id_district` INT NOT NULL,
  `id_town` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `default_address` INT NOT NULL,
  PRIMARY KEY (`account_address_id`),
  INDEX `fk_account_address_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_address_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `book_store`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(100) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`discount` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `discount_name` VARCHAR(45) NOT NULL,
  `discount_start` DATETIME NOT NULL,
  `discount_end` DATETIME NOT NULL,
  `discount_price` INT NOT NULL,
  `discount_code` VARCHAR(45) NOT NULL,
  `discount_quantity` INT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(100) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`genre_id`),
  INDEX `fk_genre_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_genre_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `book_store`.`category` (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`publish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`publish` (
  `publish_id` INT NOT NULL AUTO_INCREMENT,
  `publish_name` VARCHAR(45) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`publish_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `buy_turn` INT NOT NULL,
  `quantity` INT NOT NULL,
  `status` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image` VARCHAR(200) NOT NULL,
  `price_display` FLOAT NOT NULL,
  `percent_sale` FLOAT NOT NULL,
  `price_output` FLOAT NOT NULL,
  `price_input` FLOAT NOT NULL,
  `publish_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `pages` INT NOT NULL,
  `time_public` DATE NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`, `isbn`),
  INDEX `fk_products_publish1_idx` (`publish_id` ASC) VISIBLE,
  INDEX `fk_products_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `book_store`.`genre` (`genre_id`),
  CONSTRAINT `fk_products_publish1`
    FOREIGN KEY (`publish_id`)
    REFERENCES `book_store`.`publish` (`publish_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `rate_star` INT NOT NULL,
  `content` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `fk_feedback_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_feedback_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `book_store`.`account` (`account_id`),
  CONSTRAINT `fk_feedback_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `book_store`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`news` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `news_name` VARCHAR(100) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`news_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NOT NULL,
  `status` INT NOT NULL,
  `note` VARCHAR(1000) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `account_id` INT NOT NULL,
  `account_address_id` INT NOT NULL,
  `discount_id` INT NULL DEFAULT NULL,
  `delivery` VARCHAR(100) NOT NULL,
  `payment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_order_account_address1_idx` (`account_address_id` ASC) VISIBLE,
  INDEX `fk_order_discount1_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `book_store`.`account` (`account_id`),
  CONSTRAINT `fk_order_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `book_store`.`discount` (`discount_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`order_detail` (
  `quantity` INT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_order_detail_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_detail_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `book_store`.`order` (`order_id`),
  CONSTRAINT `fk_order_detail_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `book_store`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`order_input`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`order_input` (
  `id_order_input` INT NOT NULL AUTO_INCREMENT,
  `total` INT NOT NULL,
  `note` VARCHAR(500) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_order_input`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`order_input_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`order_input_detail` (
  `quantity` INT NOT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NULL DEFAULT NULL,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `order_input_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_order_input_detail_order_input1_idx` (`order_input_id` ASC) VISIBLE,
  INDEX `fk_order_input_detail_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_input_detail_order_input1`
    FOREIGN KEY (`order_input_id`)
    REFERENCES `book_store`.`order_input` (`id_order_input`),
  CONSTRAINT `fk_order_input_detail_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `book_store`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`products_has_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`products_has_author` (
  `product_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `author_id`),
  INDEX `fk_products_has_author_author1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_products_has_author_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `book_store`.`author` (`author_id`),
  CONSTRAINT `fk_products_has_author_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `book_store`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`rep_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`rep_feedback` (
  `rep_feedback_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` VARCHAR(45) NULL DEFAULT NULL,
  `account_id` INT NOT NULL,
  `feedback_id` INT NOT NULL,
  PRIMARY KEY (`rep_feedback_id`),
  INDEX `fk_rep_feedback_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_rep_feedback_feedback1_idx` (`feedback_id` ASC) VISIBLE,
  CONSTRAINT `fk_rep_feedback_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `book_store`.`account` (`account_id`),
  CONSTRAINT `fk_rep_feedback_feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `book_store`.`feedback` (`feedback_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`shopping_cart` (
  `Shopping_cart_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`Shopping_cart_id`),
  INDEX `fk_shopping_cart_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `book_store`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`shopping_cart_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_store`.`shopping_cart_has_products` (
  `Shopping_cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Shopping_cart_id`, `product_id`),
  INDEX `fk_shopping_cart_has_products_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_has_products_shopping_cart1_idx` (`Shopping_cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `book_store`.`products` (`product_id`),
  CONSTRAINT `fk_shopping_cart_has_products_shopping_cart1`
    FOREIGN KEY (`Shopping_cart_id`)
    REFERENCES `book_store`.`shopping_cart` (`Shopping_cart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
